name: 'Docker Publish SemVer Tags'
description: 'Tag and publish a Docker image according to Semantic Versioning'
author: 'Flownative'
inputs:
  tag_ref:
    description: 'The full tag reference. This must be a semver tag ref of an existing tagged image. For example, `refs/tags/v1.2.5+12`'
    required: true
    default: ''
  tag_latest:
    description: 'If a "latest" tag should also be created and published. Allowed values: "yes", "no", "true", "false"'
    required: false
    default: 'true'
  tag_custom:
    description: 'If a custom tag should also be created and published. If not empty, the image will be tagged with the value of this option.'
    required: false
    default: ''
  source_image_name:
    description: 'The full source image name (to be built), without tag. For example, `docker.pkg.github.com/flownative/docker-magic-image/magic-image`'
    required: true
    default: ''
  source_registry_username:
    description: 'Username for the source registry'
    required: true
    default: ''
  source_registry_password:
    description: 'Password for the source registry'
    required: true
    default: ''
  source_registry_endpoint:
    description: 'Endpoint of the source registry. For example, `https://docker.pkg.github.com/v2/`'
    required: false
    default: 'https://docker.pkg.github.com/v2/'
  target_image_name:
    description: 'The full target image name, without tag. For example, `docker.io/flownative/magic-image`'
    required: true
    default: ''
  target_registry_username:
    description: 'Username for the target registry'
    required: true
    default: ''
  target_registry_password:
    description: 'Password for the target registry'
    required: true
    default: ''
  target_registry_endpoint:
    description: 'Endpoint of the target registry. For example, `https://index.docker.io/v1/`'
    required: false
    default: 'https://index.docker.io/v1/'
outputs:
  image_tag:
    description: 'The full tag of the Docker image, e.g. "1.2.3+42" or "2.12.19-beta1+23", or ...'
  image_tag_major:
    description: 'Major version part of the image tag, e.g. "1" if the version was 1.2.3+42 '
  image_tag_minor:
    description: 'Minor version part of the image tag, e.g. "2" if the version was 1.2.3+42 '
  image_tag_patch:
    description: 'Patch version part of the image tag, e.g. "3" if the version was 1.2.3+42 '
  image_tag_patch_with_pre_release:
    description: 'Patch version part with suffix, e.g. "3+42" if the version was 1.2.3+42 '

runs:
  using: 'docker'
  image: 'docker://flownative/action-docker-publish-semver:1'
branding:
  icon: 'package'
  color: 'blue'

